### ISSUE TITLE
能支持cocoapods-generate-2.0.0 吗

### ISSUE THREAD

**Issue by robinchanme** [tripleCC/cocoapods-bin#37]
能支持cocoapods-generate-2.0.0 吗

**Comment by tripleCC** [comment]
> 能支持cocoapods-generate-2.0.0 吗

2.0.0 有什么新特性么？可以提 mr 改下 gemspec 里面的依赖版本

**Comment by robinchanme** [comment]
> > 能支持cocoapods-generate-2.0.0 吗
> 
> 2.0.0 有什么新特性么？可以提 mr 改下 gemspec 里面的依赖版本

所以只能安装 cocoapods 1.8.4
另外问一下 像SDWebImageWebPCoder 这种pod 是不支持的吗
它的依赖是以下：
`  s.dependency 'SDWebImage/Core', '~> 5.7'
`

**Comment by tripleCC** [comment]
> > > 能支持cocoapods-generate-2.0.0 吗
> > 
> > 
> > 2.0.0 有什么新特性么？可以提 mr 改下 gemspec 里面的依赖版本
> 
> 所以只能安装 cocoapods 1.8.4
> 另外问一下 像SDWebImageWebPCoder 这种pod 是不支持的吗
> 它的依赖是以下：
> ` s.dependency 'SDWebImage/Core', '~> 5.7'`

和依赖没关系

**Comment by robinchanme** [comment]
> > > > 能支持cocoapods-generate-2.0.0 吗
> > > 
> > > 
> > > 2.0.0 有什么新特性么？可以提 mr 改下 gemspec 里面的依赖版本
> > 
> > 
> > 所以只能安装 cocoapods 1.8.4
> > 另外问一下 像SDWebImageWebPCoder 这种pod 是不支持的吗
> > 它的依赖是以下：
> > ` s.dependency 'SDWebImage/Core', '~> 5.7'`
> 
> 和依赖没关系

但这个库就是并不能二进制化

**Comment by tripleCC** [comment]
> > > > > 能支持cocoapods-generate-2.0.0 吗
> > > > 
> > > > 
> > > > 2.0.0 有什么新特性么？可以提 mr 改下 gemspec 里面的依赖版本
> > > 
> > > 
> > > 所以只能安装 cocoapods 1.8.4
> > > 另外问一下 像SDWebImageWebPCoder 这种pod 是不支持的吗
> > > 它的依赖是以下：
> > > ` s.dependency 'SDWebImage/Core', '~> 5.7'`
> > 
> > 
> > 和依赖没关系
> 
> 但这个库就是并不能二进制化

```
➜  SDWebImageWebPCoder git:(master) ✗ pod bin archive --no-clean --use-libraries --verbose
^[[O[pod gen] Running with `pod gen` configuration {
  podfile_path: /Users/songruiwang/GitHub/SDWebImageWebPCoder/Podfile,
  podfile: Podfile,
  use_podfile: true,
  use_podfile_plugins: true,
  podfile_plugins: {"cocoapods-bin"=>{}},
  use_lockfile: false,
  use_lockfile_versions: false,
  use_libraries: true,
  generate_multiple_pod_projects: false,
  incremental_installation: false,
  gen_directory: /Users/songruiwang/GitHub/SDWebImageWebPCoder/bin-archive,
  auto_open: false,
  clean: true,
  podspec_paths: [#<Pathname:/Users/songruiwang/GitHub/SDWebImageWebPCoder/SDWebImageWebPCoder.podspec>],
  podspecs: [#<Pod::Specification name="SDWebImageWebPCoder">],
  sources: ["https://github.com/for-example-test/PrivateBinSpecRepo.git", "https://github.com/CocoaPods/Specs.git"],
  local_sources: [],
  repo_update: false,
  use_default_plugins: false,
  deterministic_uuids: false,
  share_schemes_for_development_pods: true,
  warn_for_multiple_pod_sources: false,
  use_modular_headers: false }

Generating SDWebImageWebPCoder in `bin-archive/SDWebImageWebPCoder`
    Cleaning gen install directory
    Creating stub application
    Writing Podfile

Installing...
Fetching podspec for `SDWebImageWebPCoder` from `../../SDWebImageWebPCoder.podspec`
Installing SDWebImage (5.9.0)
Installing SDWebImageWebPCoder (0.6.1)
Installing libwebp (1.1.0)

[!] Please close any current Xcode sessions and use `SDWebImageWebPCoder.xcworkspace` for this project from now on.
Pod installation complete! There is 1 dependency from the Podfile and 3 total pods installed.

Performing post-installation steps
    Open `bin-archive/SDWebImageWebPCoder/SDWebImageWebPCoder.xcworkspace` to work on SDWebImageWebPCoder

Building static framework SDWebImageWebPCoder (0.6.1)
  Building simulator libraries
  Building ios libraries with archs ["x86_64", "arm64", "armv7", "armv7s", "i386"]
  Copying public headers ["SDImageWebPCoder.h", "UIImage+WebP.h", "SDWebImageWebPCoder.h"]
  Writing module map framework module SDWebImageWebPCoder {   umbrella header "SDWebImageWebPCoder.h"    export *   module * { export * } }
  Copying license
Compressing SDWebImageWebPCoder.framework into SDWebImageWebPCoder.framework.zip
```

我这没问题，你报什么错？

**Comment by robinchanme** [comment]
```
robin@robinchandeMacBook-Pro SDWebImageWebPCoder % pod bin archive --no-clean --use-libraries --verbose
  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
[pod gen] Running with `pod gen` configuration {
  podfile_path: /Users/robin/suvapps/SDWebImageWebPCoder/Podfile,
  podfile: Podfile,
  use_podfile: true,
  use_podfile_plugins: true,
  podfile_plugins: {"cocoapods-bin"=>{}},
  use_lockfile: false,
  use_lockfile_versions: false,
  use_libraries: true,
  generate_multiple_pod_projects: false,
  incremental_installation: false,
  gen_directory: /Users/robin/suvapps/SDWebImageWebPCoder/bin-archive,
  auto_open: false,
  clean: true,
  podspec_paths: [#<Pathname:/Users/robin/suvapps/SDWebImageWebPCoder/SDWebImageWebPCoder.podspec>],
  podspecs: [#<Pod::Specification name="SDWebImageWebPCoder">],
  sources: ["git@gitlab.repos.suv163.com:ios/suvapp_spec_bin_dev.git", "git@gitlab.repos.suv163.com:ios/suvapp_spec_source.git"],
  local_sources: [],
  repo_update: false,
  use_default_plugins: false,
  deterministic_uuids: false,
  share_schemes_for_development_pods: true,
  warn_for_multiple_pod_sources: false,
  use_modular_headers: false }

Generating SDWebImageWebPCoder in `bin-archive/SDWebImageWebPCoder`
    Cleaning gen install directory
    Creating stub application
    Writing Podfile

Installing...
[!] CocoaPods could not find compatible versions for pod "SDWebImage/Core":
  In Podfile:
    SDWebImageWebPCoder (from `../../SDWebImageWebPCoder.podspec`) was resolved to 0.6.1, which depends on
      SDWebImage/Core (~> 5.7)

None of your spec sources contain a spec satisfying the dependency: `SDWebImage/Core (~> 5.7)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

/Users/robin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
/Users/robin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
/Users/robin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
/Users/robin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
/Users/robin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
/Users/robin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Users/robin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Users/robin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:94:in `resolve'
```

你这边是修改了podspec ？

**Comment by robinchanme** [comment]
```
Installing...
[!] The platform of the target `App-macOS` (macOS 10.13) is not compatible with `SDWebImage (5.8.4)`, which does not support `macOS`.

/Users/robin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:441:in `validate_platform'
```

这些都有要求的吗

**Comment by tripleCC** [comment]
我没修改 podspec ，是直接 clone 下来直接执行 archive 命令。有可能是 cocoapods 版本问题，我当时是 1.8 几版本。

**Comment by robinchanme** [comment]
> 我没修改 podspec ，是直接 clone 下来直接执行 archive 命令。有可能是 cocoapods 版本问题，我当时是 1.8 几版本。

好吧，我是1.9.3
